# Generated by Django 4.0.1 on 2022-01-31 13:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='CreationData',
        ),
        migrations.AddField(
            model_name='evento',
            name='creationData',
            field=models.DateTimeField(auto_now=True, verbose_name='Creation Data'),
        ),
        migrations.AddField(
            model_name='evento',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='evento',
            name='eventData',
            field=models.DateTimeField(verbose_name='Event Name'),
        ),
    ]
